### ISSUE TITLE
error callback behavior

### ISSUE THREAD

**Issue by jjb** [ostinelli/apnotic#74]
First of all, thanks for a great library!

> If the :error callback is not set, the underlying socket thread may raise an error in the main thread at unexpected execution times.

What would happen if I did this?

```ruby
connection.on(:error) { |exception| raise exception }
```

Would this be raised in the underlying socket thread, or in the main thread?

**Comment by serioushaircut** [comment]
If I may, I think I can answer this.
The callback is called from here: https://github.com/ostinelli/net-http2/blob/master/lib/net-http2/client.rb#L128
So, you don't gain much by doing this, b/c you raise from the socket thread and where the main thread is at you don't know (that is true in general - but when you use connection.push instead of connection.push_async then you'd have a good notion of where you're at in the main thread, but that is not the same as being 100% certain what the main thread does and did in between b/c that's up to apnotic and the gems 'below').
So to be certain, just log your error or better send it to an error catcher like sentry, airbrake, appsignal, or whatever, so that you gain insights what actually happened in the socket thread.

**Comment by jjb** [comment]
🆗
